### ISSUE TITLE
Apollo dataset

### ISSUE THREAD

**Issue by AcNoggano** [OpenDriveLab/PersFormer_3DLane#101]
Can you provide the implementation on the Apollo dataset? Apollo does not have the attribute of category. I found that there is a large gap between my experiment and the results in the paper. Thank you

**Comment by huangmozhi9527** [comment]
Hi, we have updated the support for the Apollo dataset.

**Comment by AcNoggano** [comment]
Can you share the epoch and batch size of the apollo dataset?

**Comment by AcNoggano** [comment]
Can you share the epoch and batch size of the apollo dataset?

**Comment by AcNoggano** [comment]
> Hi, we have updated the support for the Apollo dataset.

Can you share the epoch and batch size of the apollo dataset?

**Comment by AcNoggano** [comment]
@huangmozhi9527 Can you share the epoch and batch size of the apollo dataset?

**Comment by huangmozhi9527** [comment]
We will provide those things as soon as possible.

**Comment by huangmozhi9527** [comment]
We provide a reproduction detail, for reference only.

best epoch: 41
batch size: 8
device: 2x3090
results:
![image](https://user-images.githubusercontent.com/56259310/230730172-fcdc0c9b-65c9-47cf-b1ff-e5240b5f5536.png)

If you need the well-trained checkpoint, we will provide the checkpoint url later.

**Comment by AcNoggano** [comment]
@huangmozhi9527 hi, If it is convenient, you can send it to ieguoweizhi@163.com, thank you very much! However, the current results appear to be lower than those in the paper. I'm currently training the Vivual Variants version and the result is about 85.3
