### ISSUE TITLE
Is nms_thres value set for laneatt small?

### ISSUE THREAD

**Issue by ppbangKGT** [OpenDriveLab/PersFormer_3DLane#102]
Thanks for your great work! When I run your code and want to see the 2D Lane Detection results, I find that there often exists more predictions than gt while some of them correspond to the same gt lane. For example:
![155362886424889300](https://user-images.githubusercontent.com/76954965/223355622-2cdfe35b-a022-49fb-8002-3f16417d6615.jpg)
and this:
![150810338206595300](https://user-images.githubusercontent.com/76954965/223356106-4af97d99-9d7e-4819-9724-22917bc86f1e.jpg)
The code shows you directly save the 2D results after laneatt head and the nms_thres set for 2D is 45.0. 
So Is this caused by a small nms_thres value set for laneatt?
Thanks for your time.

**Comment by ilnehc** [comment]
Yes, this could be probably filtered if a larger NMS threshold is applied.

**Comment by ppbangKGT** [comment]
> Yes, this could be probably filtered if a larger NMS threshold is applied.

Yes, after testing, I find 60 may be better for 2D nms. Thanks for your reply.
