### ISSUE TITLE
Well-trained model question

### ISSUE THREAD

**Issue by South-River** [OpenDriveLab/PersFormer_3DLane#103]
Hi, 
Do you have the well-trained checkpoint of PersFormer under NuScenes dataset? I really need it. Could you please share them~
My e-mail address is nanhe_chen@zju.edu.cn
Thanks a lot.

**Comment by RicardLee** [comment]
We never train the PersFormer under NuScenes dataset? Do you mean that on OpenLane dataset?

**Comment by South-River** [comment]
> We never train the PersFormer under NuScenes dataset? Do you mean that on OpenLane dataset?

Sorry, my mistake. So may you share me a model trained under Openlane dataset?

**Comment by huangmozhi9527** [comment]
Hi, we have provided trained model checkpoints on the OpenLane dataset [here](https://github.com/OpenDriveLab/PersFormer_3DLane#benchmark).
