### ISSUE TITLE
Question on the Learned Loss Weights

### ISSUE THREAD

**Issue by ZhangGongjie** [OpenDriveLab/PersFormer_3DLane#104]
Thanks for the awesome work!

You mentioned in your paper that the loss weights are learned. How is it achieved? Would you please elaborate? 

Thank you in advance!

**Comment by ilnehc** [comment]
Please see:
https://github.com/OpenDriveLab/PersFormer_3DLane/blob/9ffc04c7a419c3635e1e4ec921cf12efafb86abe/models/PersFormer.py#L90-L97
