### ISSUE TITLE
how to choose top_view_region for custom dataset

### ISSUE THREAD

**Issue by AnRanbel** [OpenDriveLab/PersFormer_3DLane#106]
Hi,after i modify the (org_w,org_h) from (1920,1280) to (1640,590)，im_ipm = cv2.warpPerspective(im, H_im2ipm, (ipm_w, ipm_h)) got the black image, it seems related to top_view_region, i use the default value top_view_region = np.array([[-10, 103], [10, 103], [-10, 3], [10, 3]]). i want to know how to choose top_view_region for different scale dataset. looking forward to your reply, thank you.

**Comment by ilnehc** [comment]
The region is defined in the config file. But I think the issue might be with the transformation matrix.

**Comment by AnRanbel** [comment]
> The region is defined in the config file. But I think the issue might be with the transformation matrix. 

if (org_w,org_h)=1920,1280  work fine, but after change the scale ,output image will black. because i see in code the  transformation matrix's computation used top_view_region, so I'm wondering if the value of "top_view_region" is critical to this problem.

**Comment by AnRanbel** [comment]
> > The region is defined in the config file. But I think the issue might be with the transformation matrix. 
> 
> if (org_w,org_h)=1920,1280  work fine, but after change the scale ,output image will black. because i see in code the  transformation matrix's computation used top_view_region, so I'm wondering if the value of "top_view_region" is critical to this problem.

plus, the changed scale equal my custom image shape

**Comment by ilnehc** [comment]
I don't think the top_view region is critical. Did you adapt the intrinsic matrix accordingly?

**Comment by AnRanbel** [comment]
> I don't think the top_view region is critical. Did you adapt the intrinsic matrix accordingly?

thank you for your reply, I found out that it was the camera parameters(extrinsic/intrinsic). I used the same parameters for a sample in the openlane dataset, which didn't work on my dataset.
