### ISSUE TITLE
Could you please share more details about how the newest result in TRAIN_VAL.md is trained?

### ISSUE THREAD

**Issue by josh6688** [OpenDriveLab/PersFormer_3DLane#108]
I'm curious about the device type, device number and batch size you used when training your best model.
I also find that there is a large difference between the loss_gflat-loss of old results and newest result. Is there any changes in the config file like changes of learnable weight or optimizer settings?

**Comment by huangmozhi9527** [comment]
device type: Nvidia 3090
device number: 4
batch size: 8

We didn't change the config. As for the loss_gflat-loss, we will give an explanation as soon as possible.

**Comment by josh6688** [comment]
Thanks. That helps a lot.

**Comment by huangmozhi9527** [comment]
Hi, for the loss_gflat-loss problem, please refer to [this](https://github.com/OpenDriveLab/PersFormer_3DLane/issues/94#issuecomment-1500759378).
