### ISSUE TITLE
Error when using Apollo dataset

### ISSUE THREAD

**Issue by YangHan-Morningstar** [OpenDriveLab/PersFormer_3DLane#15]
Hi there, thanks for your excellent paper and work. I meet a bug when I use your code to train the model on Apollo dataset:

AttributeError: 'LaneDataset' object has no attribute '_label_list' 

I saw in Load_data.py when dataset is OpenLane the self._label_list will be inited in a function but when dataset is Apollo, there is no init. Could you offer a solution? Thanks a lot!

**Comment by YangHan-Morningstar** [comment]
All right, looking forward to your next version.

**Comment by huangmozhi9527** [comment]
Hi, we have updated the support for the Apollo dataset.
