### ISSUE TITLE
training with Apollo dataset

### ISSUE THREAD

**Issue by BongBong87** [OpenDriveLab/PersFormer_3DLane#29]
Thank you so much for your publication.
I tried to training with Apollo dataset (standard group in data_splits).
I got the error of no label_list.
can you give me some guide to fix this error. Thank you.
![image](https://user-images.githubusercontent.com/38457708/179437552-51ec33b0-e2ed-4968-953a-4c0d14fe437f.png)

**Comment by zihanding819** [comment]
Our current code is not fully adapted to the Apollo dataset yet. To solve your problem, try to define `self._label_list` in the init_dataset_3D function in Load_Data.py, which should be a list containing all the annotation json files paths. For reference, see the definition of `self._label_list` in `init_dataset_openlane_beta` function in Load_Data.py. And we’ll also fix this issue as soon as possible.

**Comment by huangmozhi9527** [comment]
Hi, we have updated the support for the Apollo dataset.
