### ISSUE TITLE
results based on fixed eval code [Nov 4 update]

### ISSUE THREAD

**Issue by Mollylulu** [OpenDriveLab/PersFormer_3DLane#67]
Hi, current 3D lane results are the ones from your paper, which are based on your old eval code. Can you update your results according to the fixed code? since you fixed some problems in the previous evaluation code. 
As there are several times updates of the eval code, I thought the current eval does not align with your results reported. 
thanks:)

**Comment by RicardLee** [comment]
Hi, we will update asap.

**Comment by huangmozhi9527** [comment]
Hi, we have updated the newest results using our newest eval code.
