### ISSUE TITLE
How does the Persformer consider the height of lane lines?

### ISSUE THREAD

**Issue by betterCZ101** [OpenDriveLab/PersFormer_3DLane#69]
Hi, the results of your work are impressive. But I have a question. As you mention "the height of lane lines has to be considered when we project perspective lanes into BEV space" in the paper. how does the Persformer  take the height of lane lines into consideration ? 
Whether the Persformer does just take advantage of the power of the self-attention and cross-attention mechanism to improve the performance of the normal situations such the relative even roads?

**Comment by ilnehc** [comment]
It is a great question. Compared to 1-1 mapping, the cross-attention mechanism takes surrounding areas in the image, which naturally corresponds to different heights, into consideration. Some more sophisticated ideas could be like how BEVFormer does.
