### ISSUE TITLE
Projection to ground truths to flat surface for 3D ground point generation.

### ISSUE THREAD

**Issue by artest08** [OpenDriveLab/PersFormer_3DLane#80]
Thanks for the great contribution. 

I want to ask that in the dataloader, why are we projecting 3D ground points with flat surface assumption? Is it to make the 3D points suitable for the IPM operation which is utilized for the reference point creation in the image. Aren't the actual 3D ground points are more precise and more realistic?

Thanks for your help in advance. 

https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/8d70aa431d9acd67484310299c2208bf98a0ef6c/data/Load_Data.py#L451

**Comment by huangmozhi9527** [comment]
Although 3D ground points are more precise and realistic, directly predicting 3D points from monocular image input is tough. So a common solution is BEV transformation.

Some papers also try to predict 3D points directly (e.g., Anchor3DLane). Maybe you can get some insights from them.
