### ISSUE TITLE
error in ms_deformable_im2col_cuda: invalid configuration argument

### ISSUE THREAD

**Issue by meghana-shastri24** [OpenDriveLab/PersFormer_3DLane#86]
Hi @RicardLee,

"error in ms_deformable_im2col_cuda: invalid configuration argument" is printed for every validation iteration. But it does not stop the training nor the validation. Could you please suggest what could be the issue for this error message?

Thanks in advance.

**Comment by huangmozhi9527** [comment]
Sorry, we haven't met this problem. The unmatched version between Pytorch and CUDA might cause this. Can you get the right results in this situation? Or you can provide your environment yaml file and detailed logs.
