### ISSUE TITLE
ipm_w problem

### ISSUE THREAD

**Issue by AcNoggano** [OpenDriveLab/PersFormer_3DLane#89]
hi, In the code, ipm_w is set to 128, but in the Implementation Details section, Bev is set to 208 * 108. Whether the two data should correspond to each other or not?

**Comment by AcNoggano** [comment]
hi, the results in the [TRAIN_VAL.md](https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/main/docs/TRAIN_VAL.md#evaluation) are not the same as the results in the [Benchmark,](https://github.com/OpenPerceptionX/PersFormer_3DLane#benchmark), especially in the x and z indicators, the difference is huge, which one is worthy of reference

**Comment by huangmozhi9527** [comment]
Sorry, the ipm_w of 108 in the paper is an mistake, please subject to the code. And we have unified the newest results in [TRAIN_VAL.md](https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/main/docs/TRAIN_VAL.md#evaluation) and [Benchmark](https://github.com/OpenPerceptionX/PersFormer_3DLane#benchmark).

**Comment by huangmozhi9527** [comment]
Sorry, the ipm_w of 108 in the paper is a mistake, please subject to the code. And we have unified the newest results in [TRAIN_VAL.md](https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/main/docs/TRAIN_VAL.md#evaluation) and [Benchmark](https://github.com/OpenPerceptionX/PersFormer_3DLane#benchmark).
