### ISSUE TITLE
Error when testing in ONCE_3DLane dataset

### ISSUE THREAD

**Issue by ppbangKGT** [OpenDriveLab/PersFormer_3DLane#92]
Thanks for your great work! When I use your model for ONCE_3DLane dataset to test performance, it come out an error. The error seems to occur when computing weighted std based on visibility. I put the screenshot below:
![1671195911042](https://user-images.githubusercontent.com/76954965/208104733-b9dce71f-723f-4e07-b07e-45418df58e5f.png)
I wonder if you met the same problem when you train/test the model. Thanks for your time.

**Comment by wohaiyo** [comment]
I have the same problem, have you solved it?

**Comment by ppbangKGT** [comment]
> I have the same problem, have you solved it?

I have solved, but it has been a long time passed......
I guess rearrange your directory of ONCE_3DLane dataset maybe help.

**Comment by pocky111** [comment]
> > I have the same problem, have you solved it?
> 
> I have solved, but it has been a long time passed...... I guess rearranging your directory of ONCE_3DLane dataset may help.

我可以向您请教具体数据集如何排列吗

**Comment by PumpkinCCC** [comment]
> > > 我也有同样的问题，你解决了吗？
> > 
> > 
> > 我已经解决了，但是已经过去很长时间了……我想重新排列 ONCE_3DLane 数据集的目录可能会有所帮助。
> 
> 我可以向您请具体教数据集如何排列吗

您好，我也遇到了相同的问题，请问可以请教一下您是怎么排列数据集的吗？

> > I have the same problem, have you solved it?
> 
> I have solved, but it has been a long time passed...... I guess rearranging your directory of ONCE_3DLane dataset may help.

Hello, I have encountered the same problem. May I ask how you arrange the data set?
