### ISSUE TITLE
about average loss_gflat-loss on validation set

### ISSUE THREAD

**Issue by nicko1233** [OpenDriveLab/PersFormer_3DLane#94]
Hello, I use the [1.1  version](https://github.com/OpenPerceptionX/PersFormer_3DLane#benchmark) of the model for testing, and I found that several benchmarks are normal, but why is there such a big gap between the loss on the validation set and the [document](https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/main/docs/TRAIN_VAL.md#evaluation)?
![QQ截图20230104124147](https://user-images.githubusercontent.com/48404905/210486586-aa78cbc5-c56e-4242-ab67-ffddeaf3ee24.jpg)

**Comment by AcNoggano** [comment]
I also encountered this problem, did you solve it?

**Comment by huangmozhi9527** [comment]
Hi, this problem is caused by abnormal 2D regression loss. When transforming 2D gt points from 3D gt points, some out-image 2D gt points will have huge values (e.g., 10646.24517136). Those out-image 2D gt points will lead to a huge 2D regression loss.
