### ISSUE TITLE
Anchor design on OpenLane dataset 

### ISSUE THREAD

**Issue by javierpastorfernandez** [OpenDriveLab/PersFormer_3DLane#96]
Hi, I am opening this issue to ask how are anchors handled with Openlane Dataset.
There is no explanation on how does the anchor handle horizontal cases. Also, the dataset itself is not prepared for anchor design, meaning that a unique lane instance is divided into several lanemarkings with different lanemarking categories. This prevents training a network that is anchor-based.

How are you dealing with this lane-merging pre-processing step?

**Comment by ilnehc** [comment]
Yes, you get the point. We think the anchor-based design is difficult to solve the proposed problem.
